CREATE TABLE Genre (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    Label VARCHAR(55) NOT NULL
);

CREATE TABLE Artist (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    ArtistName VARCHAR(55) NOT NULL,
    YearEstablished INTEGER NOT NULL
);

CREATE TABLE Album (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    Title VARCHAR(55) NOT NULL,
    ReleaseDate VARCHAR(55) NOT NULL,
    AlbumLength INTEGER NOT NULL,
    Label VARCHAR(55) NOT NULL,
    ArtistId INTEGER NOT NULL,
    GenreId INTEGER,
    CONSTRAINT FK_Album_Artist FOREIGN KEY(ArtistId) REFERENCES Artist(Id),
    CONSTRAINT FK_Album_Genre FOREIGN KEY(GenreId) REFERENCES Genre(Id)
);

CREATE TABLE Song (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    Title VARCHAR(55) NOT NULL,
    SongLength INTEGER NOT NULL,
    ReleaseDate VARCHAR(55) NOT NULL,
    GenreId INTEGER,
    ArtistId INTEGER NOT NULL,
    AlbumId INTEGER NOT NULL,
    CONSTRAINT FK_Song_Genre FOREIGN KEY(GenreId) REFERENCES Genre(Id),
    CONSTRAINT FK_Song_Artist FOREIGN KEY(ArtistId) REFERENCES Artist(Id),
    CONSTRAINT FK_Song_Album FOREIGN KEY(AlbumId) REFERENCES Album(Id)
);

